### ISSUE TITLE
String(char * str, size_t length);

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#10]
What is length used for?

**Comment by jaspersong** [comment]
Constructor had been removed in order to be inline with the class standard for object.h and string.h seen on commit [d2a560108bad6b08316e6e3d159968b2dadfd160](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/d2a560108bad6b08316e6e3d159968b2dadfd160)

Standard taken from [this repo](https://github.com/chasebish/cwc_object_string) at [piazza post @345](https://piazza.com/class/k51bluky59n2jr?cid=345)
