### ISSUE TITLE
Empty queue equality

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#16]
t_false(q2->equals(q1));

This should be true since both are empty. Also, if you put the same items in the "typed" queue, they should depend on the equality of its contents.

**Comment by jaspersong** [comment]
Updated in commit [0543b780d946ef014440d37595c291ac0e0635f6](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/0543b780d946ef014440d37595c291ac0e0635f6)

**Comment by jjones-99** [comment]
This is actually dependent on the spec itself. If the spec pair wants an empty `Queue` of `String`s and an empty `Queue` of `Object`s to be 'equal', then it should be `t_true`.

IMO, those don't seem like they should be equal since they can't be used in the same way. In that case, it should be `t_false`.

@jaspersong, could you clarify which specification your pair wants?

**Comment by jaspersong** [comment]
We had preferred having the two types of queues be different, due to the fact that they support entirely different data structures/types, but we understood the decision of having the queues be compared by content, rather than content and functionality in tangem. So we decided to pick our fights, and update the tests accordingly.

Since it's getting very late in the week, and the assignment is due tomorrow, we decided that we won't be reverting the changes. The assignment has too many shifting goalposts as is, so I don't want to shift any goal posts for you guys either. 

Good luck on your assignment!
